title   : Nathaniel Kong Memorial
description: Lover of Christ and the Church and a loving shepherd
full_name: Nathaniel Kong
date_range: October 14, 1962 - February 28, 2022
hero_background_color: 004A80
headline: Lover of Christ and the Church and a loving shepherd
navigation:
  - titles:
      en: Biography
    url: /biography.html

  - titles:
      en: Family
    url: /archive.html?tag=family
  - titles:
      en: Saints
    url: /archive.html?tag=saints
  - titles:
      en: Friends
    url: /archive.html?tag=friends

  - titles:
      en: Videos
    url: /videos.html
  - titles:
      en: Photos
    url: /photos.html

memorial_meeing:
    datetime: March 19th 10am-12pm
    venue: Mack Powell Event Center
    address: 2003 Howe Ave, Sacramento, CA 95825

biography:
  title: A Short Biography of Nathaniel Kong
  subtitle: “A Life Out-poured”

video_ids:
  - kWM4X1gA56U
  - p5RSornvPgU
  - hkyQqltBeLI
  - bIktm0ka6o0
  - XTZRkb8r59E
  - 5CWW3QpZQkg
  - TCur3_4X6RY
  - YrtiHh_GLnU
