title   : Nathaniel Kong Memorial
description: A Lover of Christ and the Church and A Loving Shepherd
full_name: Nathaniel Kong
date_range: October 14, 1962 - February 28, 2022
hero_background_color: 004A80
headline: Lover of Christ and the Church and a loving shepherd
navigation:
  - titles:
      en: Biography
    url: /biography.html

  - titles:
      en: Family
    url: /archive.html?tag=family
  - titles:
      en: Saints
    url: /archive.html?tag=saints
  - titles:
      en: Friends
    url: /archive.html?tag=friends

  - titles:
      en: Videos
    url: /videos.html
  - titles:
      en: Photos
    url: /photos.html

memorial_meeing:
    datetime: March 19th 10am-12pm
    venue: Mack Powell Event Center
    address: 2003 Howe Ave, Sacramento, CA 95825

biography:
  title: A Short Biography of Nathaniel Kong
  subtitle: “A Life Outpoured”

authors:
  Wanchi:
    name: Wanchi Kong
  Joseph:
    name: Joseph Kong

videos:
  -
    id: YrtiHh_GLnU
    title: Until the Chens Arrive
  -
    id: TCur3_4X6RY
    title: Volleyball
  -
    id: bIktm0ka6o0
    title: Skateboarding
  -
    id: kWM4X1gA56U
    title: Bible Camp 2020 Theme Song
  -
    id: hkyQqltBeLI
    title: Greeting Our Relative
  -
    id: p5RSornvPgU
    title: Building the Fire
  -
    id: QLc_iNbG7vY
    title: Planning a Greeting
  -
    id: p58IxsFlGKQ
    title: Cry Out and Shout (Hallelujah)!
  -
    id: QDRCGZ5R6Ic
    title: Manning the Zoom Camera
  -
    id: QDRCGZ5R6Ic
    title: Playing Biblical Heads Up
  -
    id: DrrS43zu3Rk
    title: Bible Study on God's Love
  -
    id: 9AiN_zx0Ai8
    title: Volleyball the Setter
  -
    id: 6XRuqkpyoC4
    title: On a Trail in Munich
  -
    id: VRGbvrTKXPg
    title: Singing at a Sac State Bible Study
  -
    id: a5LP3NvwR0o
    title: Oh Lord, Amen, Hallelujah, Jesus!
  -
    id: XTZRkb8r59E
    title: IMG 0044
