title   : 吳梁蘭英 師母
description: 婆婆
full_name: 吳梁蘭英 
date_range: October 14, 1962 - February 28, 2022
hero_background_color: 004A80
headline: 追思
navigation:
  - titles:
      en: Biography
    url: /biography.html
  - titles:
      en: Family
    url: /archive.html?tag=family
  - titles:
      en: Saints
    url: /archive.html?tag=saints
  - titles:
      en: Photos
    url: /photos.html
  - titles:
      en: Videos
    url: /videos.html  
biography:
  title: 吳梁蘭英
  subtitle: “A Life Outpoured”